version: 2

# https://docs.getdbt.com/reference/configs-and-properties

sources:
  - name: faker__orders
    description: Faker dummy data
    database: dbt_analytics
    schema: raw_faker
    tags: ['stg', 'faker']

    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: faker_orders_customer
        description: Raw customer data from Faker source.
        columns:
          - name: customer_id
            description: Primary key
            tests:
              - not_null:
                  severity: warn
          - name: customer_name
            description: Full name of customer
            tests:
              - not_null:
                  severity: warn
          - name: email
            description: Customer email
            tests:
              - not_null:
                  severity: warn
          - name: country
            description: Country of origin
            tests:
              - not_null:
                  severity: warn

      - name: faker_orders_product
        description: Raw product data from Faker source.
        columns:
          - name: product_id
            description: Primary key
            tests:
              - not_null:
                  severity: warn
          - name: product_name
            description: Product name
            tests:
              - not_null:
                  severity: warn
          - name: category
            description: Product category
            tests:
              - not_null:
                  severity: warn

      - name: faker_orders_orders
        description: Raw order data from Faker source.
        loaded_at_field: created_ts    # <==== Freshness tracking uses this timestamp
        columns:
          - name: order_id
            description: Primary key
            tests:
              - not_null:
                  severity: warn
          - name: customer_id
            description: Foreign key to dim_customer
            tests:
              - not_null:
                  severity: warn
          - name: order_date
            description: Date the order was placed
            tests:
              - not_null:
                  severity: warn
          - name: currency_id
            description: Currency used in transaction
            tests:
              - not_null:
                  severity: warn

      - name: faker_orders_order_items
        description: Raw order item data from the Faker source system.
        loaded_at_field: created_ts    # <==== Freshness tracking uses this timestamp
        columns:
          - name: order_id
            description: Foreign key to fact_orders
            tests:
              - not_null:
                  severity: warn
          - name: product_id
            description: Foreign key to dim_product
            tests:
              - not_null:
                  severity: warn
          - name: quantity
            description: Quantity of product sold
            tests:
              - not_null:
                  severity: warn
          - name: unit_price
            description: Unit price of the product
            tests:
              - not_null:
                  severity: warn
          - name: order_date
            description: Date the order was placed (copied from orders)
            tests:
              - not_null:
                  severity: warn
          - name: created_ts
            description: Timestamp when the order was created (copied from orders)
            tests:
              - not_null:
                  severity: warn
          - name: updated_ts
            description: Timestamp when the order was last updated (copied from orders)
            tests:
              - not_null:
                  severity: warn
                  enabled: false

models:
  - name: stg_faker_orders_currency
    description: Staging model for currency seed data from Faker.
    columns:
      - name: currency_code
        description: ISO currency code (e.g., USD, EUR)
        tests:
          - not_null
          - unique
      - name: currency_name
        description: Full currency name (e.g., US Dollar)
        tests:
          - not_null
      - name: currency_symbol
        description: Symbol representation (e.g., $, €)
        tests:
          - not_null
