name: 'dbt_pipeline'
version: '1.0.0'
config-version: 2

profile: 'dbt_pipeline'

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]
docs-paths:     ["docs"]

dispatch:
  - macro_namespace: dbt_utils
    search_order: ["dbt_pipeline", "dbt_utils"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_pipeline:
    +materialized: ephemeral

    staging:
      +materialized: view
      +database:  dwh
      +schema:    stg
      +enabled:   true
      +tags:      ['stg']

    intermediate:
      +materialized: view
      +database:  dwh
      +schema:    int
      +enabled:   true
      +tags:      ['int']

    marts:
      +materialized: table
      +database:  reporting
      +schema:    marts
      +enabled:   true
      +tags:      ['marts']
      +grants:
          select: ["analyst", "developer"]
      +severity: error

tests:
  +store_failures: false
  +severity:      warn

quoting:
  database:   false
  schema:     false
  identifier: false


on-run-start: []

on-run-end: []
 
