# enforce a dbt version range so your CI/CD always runs on a known release
require-dbt-version: [">=1.0.0", "<2.0.0"]

name: 'dbt_pipeline'
version: '1.0.0'
config-version: 2

profile: 'dbt_pipeline'
 
# -------------------------------------------------------------------
#  Paths
# -------------------------------------------------------------------
model-paths:        ["models"]
analysis-paths:     ["analyses"]
test-paths:         ["tests"]
seed-paths:         ["seeds"]
macro-paths:        ["macros"]
snapshot-paths:     ["snapshots"]
docs-paths:         ["docs"]

dispatch:
  - macro_namespace: dbt_utils
    search_order: ["dbt_pipeline", "dbt_utils", "dbt"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# -------------------------------------------------------------------
#  Global model defaults
# -------------------------------------------------------------------
# Note: Database and schema names below define the *production* targets.
#       Non-prod runs (dev/stg) will be routed via custom macros:
#         - generate_database_name(custom_db, node)
#         - generate_schema_name(custom_schema, node)
#       These macros override to target.database and target.schema for dev/stg.

models:
  dbt_pipeline:
    # Model schemas are for Prod runs. The generate macros will override if not running in Prod and put into target schema.

    # Put all tranformation objects into the transform schema.
    +materialized:  view
    +database:      dwh
    +schema:        transform
    +tags:          ['stg', 'int', 'transform']
    +severity:      warn

    marts:
      +materialized: table
      +database:     reporting
      +schema:       marts
      +tags:         ['marts']
      +severity:     error
      +post-hook:    "{% if target.name == 'prod' %}{{ log_model_run() }}{% endif %}"

    # Persist docs to the database (relation & column comments)
    +persist_docs:
      relation: true
      columns:  true

# ──────────────────────────────────────────────────────────────────────────────
#  SNAPSHOTS
# ──────────────────────────────────────────────────────────────────────────────
snapshots:
  dbt_pipeline:
    +database:  dwh
    +schema:    snapshots 
    +enabled:   "{{ target.name == 'prod' }}"

# -------------------------------------------------------------------
#  Tests
# -------------------------------------------------------------------
tests:
  +store_failures:  false
  +severity:        warn

# -------------------------------------------------------------------
#  Quoting
# -------------------------------------------------------------------
quoting:
  database:   false
  schema:     false
  identifier: false

# -------------------------------------------------------------------
#  Project-level vars
# -------------------------------------------------------------------
vars:
  analyst_role:         analyst_role
  developer_role:       developer_role
  raw_ingest_svc_role:  raw_ingest_svc_role
  reporting_svc_role:   reporting_svc_role
  transform_svc_role:   transform_svc_role
 
# -------------------------------------------------------------------
#  Hooks
# -------------------------------------------------------------------
on-run-start: []
on-run-end:   []
