# seeds/faker/orders/schema.yml
version: 2

seeds:
  - name: faker_orders_currency
    config:
      tags: ['seed', 'faker']
      column_types:
        currency_id:     varchar
        currency_code:   varchar
        currency_name:   varchar
        currency_symbol: varchar
