version: 2

models:
  - name: dim_date
    description: "Date dimension from 2010-01-01 to 2030-12-31, used for joining to event or order dates."
    columns:
      - name: date_dt
        description: "The actual date (primary key)."
        tests:
          - not_null
          - unique
      - name: year
        description: "Calendar year."
      - name: month
        description: "Month number (1–12)."
      - name: month_name
        description: "Full name of the month (e.g., 'January')."
      - name: quarter
        description: "Quarter of the year (1–4)."
      - name: day_of_month
        description: "Day of the month (1–31)."
      - name: day_of_week
        description: "Day of the week (1=Sunday, 7=Saturday)."
      - name: weekday_name
        description: "Full name of the weekday."
      - name: is_weekend
        description: "TRUE if Saturday or Sunday, else FALSE."
      - name: is_holiday
        description: "Placeholder for holiday flag (always FALSE for now)."



  - name: dim_time
    description: Dimension table representing every minute of the day, with AM/PM and audit metadata.
    columns:
      - name: time_ts
        description: Timestamp for the minute of day (HH:MM:00)
        tests:
          - not_null
          - unique

      - name: hour
        description: Hour component of the timestamp (0–23)

      - name: minute
        description: Minute component of the timestamp (0–59)

      - name: second
        description: Always 0

      - name: am_pm
        description: Text label for AM/PM

      - name: record_loaded_ts
        description: Audit column from macro

      - name: dbt_invocation_id
        description: Audit column from macro

      - name: dbt_run_ts
        description: Audit column from macro

      - name: model_name
        description: Audit column from macro
