{% macro prod_grants() %}
{% if target.name == 'prod' %}

-- 0) create schemas if they don’t exist
CREATE SCHEMA IF NOT EXISTS DBT_ANALYTICS.STG;
CREATE SCHEMA IF NOT EXISTS DBT_ANALYTICS.INT;
CREATE SCHEMA IF NOT EXISTS DBT_ANALYTICS.MARTS;

-- 1) ETL_ROLE: all rights on all schemas
GRANT ALL ON ALL SCHEMAS IN DATABASE DBT_ANALYTICS TO ROLE ETL_ROLE;

-- 2) DEV_ROLE: usage+select on all schemas/tables
GRANT USAGE ON ALL SCHEMAS IN DATABASE DBT_ANALYTICS TO ROLE DEV_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE DBT_ANALYTICS TO ROLE DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE DBT_ANALYTICS TO ROLE DEV_ROLE;

-- 3) ANALYST_ROLE: usage on MARTS only
GRANT USAGE ON SCHEMA DBT_ANALYTICS.MARTS TO ROLE ANALYST_ROLE;

{% endif %}
{% endmacro %}
