name: dbt Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install linters & dbt
        run: |
          pip install --upgrade pip
          pip install \
            "yamllint>=1.32.0,<2.0" \
            "sqlfluff>=3.0,<4.0"

      - name: Lint YAML
        run: yamllint -c ./.yamllint.yml .

      - name: Lint only changed SQL
        run: |
          git fetch origin main
          git diff --name-only origin/main...HEAD \
            | grep '\.sql$' \
            | xargs -r sqlfluff lint --dialect snowflake --templater jinja .
