name: dbt Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install linters & dbt
        run: |
          pip install --upgrade pip
          pip install \
            yamllint==1.32.0 \
            sqlfluff==1.4.5 \
            sqlfluff-templater-dbt==1.4.5 \
            dbt-core==1.4.5 \
            dbt-snowflake==1.4.5

      - name: Lint YAML
        run: yamllint -c ./.yamllint.yml .

      - name: Lint SQL & Jinja
        run: sqlfluff lint --dialect snowflake --templater dbt .
