name: Publish dbt Docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pages: write   # allow pushing to gh-pages
      id-token: write
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    # so gh-pages pushes have full history

      - name: Set up Python & dbt
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run dbt deps, generate, and compile docs
        uses: dbt-labs/dbt-action@v1
        with:
          project-dir: .          # your dbt project root
          install-deps: true      # runs `dbt deps` for you
          args: docs generate     # runs `dbt docs generate`

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target   # dbt writes your docs site here
          publish_branch: gh-pages
