name: Generate dbt Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt and dependencies
        run: |
          pip install dbt-core dbt-snowflake
          dbt deps

      - name: Generate docs
        run: dbt docs generate --no-profile

      - name: List generated docs files
        run: ls -R target/
