name: Publish dbt Docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python & dbt
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt & adapter
        run: |
          pip install dbt-core dbt-snowflake

      - name: Run dbt deps, generate, and compile docs
        uses: dbt-labs/dbt-action@v1
        with:
          project-dir: .
          install-deps: true
          args: docs generate

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
          publish_branch: gh-pages
