name: Generate dbt Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt and dependencies
        run: |
          pip install dbt-core dbt-snowflake
          dbt deps

      - name: Create dummy profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
default:
  target: dummy
  outputs:
    dummy:
      type: snowflake         # or your adapter
      account: fake
      user: fake
      password: fake
      role: fake
      database: fake
      warehouse: fake
      schema: fake
EOF

      - name: Generate docs
        run: dbt docs generate

      - name: List generated docs files
        run: ls -R target/
