# .github/workflows/refresh-covid-csv-to-s3.yml
name: Refresh OWID COVID Data to S3

on:
  schedule:
    # Every Sunday at 01:00 UTC
    - cron: '0 1 * * 0'
  workflow_dispatch: {}

jobs:
  refresh-csv:
    runs-on: ubuntu-latest
    timeout-minutes: 15    # cancel the job if it runs longer than 15 min
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download latest OWID COVID dataset
        run: |
          mkdir -p data
          curl -sSL -o data/owid-covid-data.csv \
            https://covid.ourworldindata.org/data/owid-covid-data.csv

      - name: Upload OWID CSV to S3
        run: |
          aws s3 cp \
            data/owid-covid-data.csv \
            s3://ramsaier-covid-data-us-east/owid/owid-covid-data.csv \
            --acl bucket-owner-full-control
